[package]
name = "cli_test"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.13"
clap = { version = "4.5.21", features = ["derive"] }
predicates = "3.1.2"
pretty_assertions = "1.4.0"
