[package]
name = "rusty-journal"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
